import Foundation

// MARK: - Multi-Modal Ensemble Report

/// A combined analysis report synthesizing PINN results from multiple spectral domains
/// for the same sample material.
struct MultiModalReport: Sendable {
    let sampleName: String
    let generatedAt: Date
    let domainResults: [DomainResultSummary]
    let crossDomainInsights: [String]
    let materialCharacterization: String
    let consistencyAssessment: String
    let recommendations: [String]
    let risks: [String]

    /// Summary of a single domain's PINN prediction within the multi-modal report.
    struct DomainResultSummary: Sendable, Identifiable {
        let id: UUID
        let domain: PINNDomain
        let prediction: PINNPredictionResult
        let keyFindings: [String]

        init(domain: PINNDomain, prediction: PINNPredictionResult, keyFindings: [String]) {
            self.id = UUID()
            self.domain = domain
            self.prediction = prediction
            self.keyFindings = keyFindings
        }
    }

    /// Generates a markdown-formatted report string suitable for OOXMLWriter.
    func toMarkdown() -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .medium
        dateFormatter.timeStyle = .short

        var lines: [String] = []

        lines.append("# Combined Multi-Modal Analysis Report")
        lines.append("")
        lines.append("**Sample:** \(sampleName)")
        lines.append("**Generated:** \(dateFormatter.string(from: generatedAt))")
        lines.append("**Domains Analyzed:** \(domainResults.map(\.domain.displayName).joined(separator: ", "))")
        lines.append("")

        // Executive Summary
        lines.append("## Executive Summary")
        lines.append("")
        lines.append(materialCharacterization)
        lines.append("")

        // Per-Domain Results
        lines.append("## Domain Results")
        lines.append("")
        for result in domainResults {
            lines.append("### \(result.domain.displayName)")
            lines.append("")
            lines.append("**\(result.prediction.primaryLabel):** \(result.prediction.formatted)")
            lines.append("**Physics Consistency:** \(String(format: "%.0f%%", result.prediction.physicsConsistencyScore * 100))")
            lines.append("")
            if !result.keyFindings.isEmpty {
                for finding in result.keyFindings {
                    lines.append("- \(finding)")
                }
                lines.append("")
            }
        }

        // Cross-Domain Insights
        if !crossDomainInsights.isEmpty {
            lines.append("## Cross-Domain Insights")
            lines.append("")
            for insight in crossDomainInsights {
                lines.append("- \(insight)")
            }
            lines.append("")
        }

        // Consistency Assessment
        lines.append("## Consistency Assessment")
        lines.append("")
        lines.append(consistencyAssessment)
        lines.append("")

        // Recommendations
        if !recommendations.isEmpty {
            lines.append("## Recommendations")
            lines.append("")
            for rec in recommendations {
                lines.append("- \(rec)")
            }
            lines.append("")
        }

        // Risks
        if !risks.isEmpty {
            lines.append("## Risks & Limitations")
            lines.append("")
            for risk in risks {
                lines.append("- \(risk)")
            }
            lines.append("")
        }

        lines.append("---")
        lines.append("*Generated by PhysicAI — Physics-Informed Neural Network Multi-Modal Analysis*")

        return lines.joined(separator: "\n")
    }

    /// Generates the standard file name for this report.
    var suggestedFileName: String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd_HHmmss"
        let sanitizedName = sampleName
            .replacingOccurrences(of: " ", with: "_")
            .replacingOccurrences(of: "/", with: "-")
        return "Combined_Multi-Modal_Report_\(sanitizedName)_\(dateFormatter.string(from: generatedAt)).docx"
    }
}
